spring:
  datasource:
    #内网
    url: jdbc:mysql://rm-j0bt8woy1xl618o5235640.mysql.australia.rds.aliyuncs.com:3306/mee_store?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    #外网
    #url: jdbc:mysql://rm-j0bt8woy1xl618o52so.mysql.australia.rds.aliyuncs.com:3306/mee_store?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: mee_store
    password: AvRYwTFZpmTEdo/5ACiKnwGk6KgXwQSBHoTfeJTOZyWkr69+GuRj7FqmGNL0TjL1MmdnUlOIuFN+MkF0paYEPw==
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;
      initial-size: 5
      min-idle: 5
      max-active: 20
      test-on-borrow: true
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-While-Idle: true
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      filters: config,stat,wall,log4j
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        #allow:
        # IP黑名单 (存在共同时，deny优先于allow)
        #deny:
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: admin
        # 登录密码
        login-password: 123456
  servlet:
    multipart:
      # 上传一个文件最大值,默认1Mb
      max-file-size: 2MB
      # 上传多个文件最大值,50Mb,默认10Mb
      max-request-size: 2MB
  jackson:
    default-property-inclusion: NON_NULL
    date-format: yyyy/MM/dd HH:mm:ss
    #generator:
      #write-numbers-as-strings: true

  mail:
    host: smtp.gmail.com
    port: 465
    username: harryzhao0211@gmail.com
    password: fmyexjwstwrwukha
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8801

mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: true

mee:
  ocrApiKey: 2259c1572d88957
  ocrUrl: https://api.ocr.space/parse/image
  allProductUrl: https://biz.yiyun.co.nz/api/getAllProducts
  allSupplieUrl: https://biz.yiyun.co.nz/api/getAllSuppliers
  bizUsersUrl: https://biz.yiyun.co.nz/api/getBizUsers
  bizSalesUrl: https://biz.yiyun.co.nz/api/getSales
  currencyUrl: https://free.currconv.com/api/v7/convert
  currencyKey: 38e1d5b13ec68a54defa
  stockIntake: https://biz.yiyun.co.nz/api/stockIntake
  expressUrl: http://www.kuaidi100.com/autonumber/auto
  expreeKey: KgeLmhNI9486
  kdnUserId: 1614896
  kdnKey: 314f2549-7760-4c5d-9f28-3940b25d3dea
  kdnNumberIdentifyUrl: http://api.kdniao.com/Ebusiness/EbusinessOrderHandle.aspx
  newsUrl: https://newsapi.org/v2/top-headlines
  startDate: 2019-01-01
  weimob:
    clientId: 73CB87739147019B0A185720E6ED1EC9
    clientSecret: C25CD25C2051AF6B5F9DA36737736457
    weimobTokenUrl: https://dopen.weimob.com/fuwu/b/oauth2/token
    weimobOrderListUrl: https://dopen.weimob.com/api/1_0/ec/order/queryOrderList
    returnUri: https://external.yiyun.co.nz/data/index.html?page=weimob
    goodsClassifyUrl: https://dopen.weimob.com/api/1_0/ec/goodsClassify/queryClassifyInfoList
    goodListUrl: https://dopen.weimob.com/api/1_0/ec/goods/queryGoodsList
    orderDetail: https://dopen.weimob.com/api/1_0/ec/order/queryOrderDetail
    updateGoodUrl: https://dopen.weimob.com/api/1_0/ec/goods/updateStockAndPrice
    goodDetailUrl: https://dopen.weimob.com/api/1_0/ec/goods/queryGoodsDetail
    batchDeliveryUrl: https://dopen.weimob.com/api/1_0/ec/order/batchDeliveryOrder
    orderDeliveryUrl: https://dopen.weimob.com/api/1_0/ec/order/deliveryOrder
    flagOrderUrl: https://dopen.weimob.com/api/1_0/ec/order/updateOrderFlag

  ymtou:
    appId: IkCIPGv4SCYNhVQ0z9
    appSecret: Ot03NvC9g8tFu8NiDgc0OXixhhBQj5Zy
    authCode: 03X7LWDxM6A568ratg8phvheQ6Wgm5GK
    url: https://open.ymatou.com/apigateway/v1

  nineteen:
    orderListUrl: https://api.wfcorp.cn/shop/v1/Identity/orderInfo
    productUrl: https://api.wfcorp.cn/shop/v1/Identity/productsInfo
    productTypeUrl: https://api.wfcorp.cn/shop/v1/Identity/goodTypeInfo
    productGroupUrl: https://api.wfcorp.cn/shop/v1/Identity/goodGroupInfo
    editProductUrl: https://api.wfcorp.cn/shop/v1/Identity/productsEdit
    logisticsUrl: https://api.wfcorp.cn/shop/v1/Identity/logistics
    deliveryUrl: https://api.wfcorp.cn/shop/v1/Identity/manualDeliver

  flyway:
    # tokenUrl: https://flywayauthapi.azurewebsites.net/api/auth
    tokenUrl: https://flywayclientwebappauthapi.azurewebsites.net/api/Auth
    addOrderUrl: https://flywaywebappapi.azurewebsites.net/api/AddOrders

  trademe:
    #key: 7670C2A492CBC90325E9F1FB8ED989FE     
    #secret: E647F45EE7700D74940605815F7D7407
    key: B7B9BE9F74FFE26A6ED3CCA0394102D6
    secret: 724C902437D31E55FB58665C3A2EE2D6
    tokenUrl: https://secure.tmsandbox.co.nz/Oauth/RequestToken
    accessTokenUrl: https://secure.tmsandbox.co.nz/Oauth/AccessToken
    callbackUrl: https://external.yiyun.co.nz/trademe
    profileUrl: https://api.tmsandbox.co.nz/v1/MyTradeMe/Summary.JSON
    soltItemUrl: https://api.tmsandbox.co.nz/v1/MyTradeMe/SoldItems
    editStatusUrl: https://api.tmsandbox.co.nz/v1/MyTradeMe/Status
    noteUrl: https://api.tmsandbox.co.nz/v1/MyTradeMe/Notes.JSON
  nzpost:
    # clientId: 82f3c23906524e888e189f1311998545
    clientId: b5dc889df1db48abba2705e7317f966f
    # secret: e9152484081A4850a56a1804FFDF05D1
    secret: d4fDe946CBE84155B333ba5a44825941
    # siteCode: 77457
    siteCode: 68669
    #accessTokenUrl: https://oauth.nzpost.co.nz/as/token.oauth2
    accessTokenUrl: https://oauth.uat.nzpost.co.nz/as/token.oauth2    
    #createLabelUrl: https://api.nzpost.co.nz/parcellabel/v3/labels
    createLabelUrl: https://api.uat.nzpost.co.nz/parcellabel/v3/labels
    #shippedOptionUrl: https://api.nzpost.co.nz/shippingoptions/2.0/domestic
    shippedOptionUrl: https://api.uat.nzpost.co.nz/shippingoptions/2.0/domestic
    #statusOfLabelUrl: https://api.nzpost.co.nz/parcellabel/v3/labels
    statusOfLabelUrl: https://api.uat.nzpost.co.nz/parcellabel/v3/labels
    bookingUrl: https://api.uat.nzpost.co.nz/parcelpickup/v3/bookings

